export const CALC_SHOPPING_LIST_SAGA = 'CALC_SHOPPING_LIST_SAGA';
export const CALC_SHOPPING_LIST = 'CALC_SHOPPING_LIST';

export const GET_AVAILABLE_PRODUCTS = 'GET_AVAILABLE_PRODUCTS';
export const GET_AVAILABLE_PRODUCTS_SAGA = 'GET_AVAILABLE_PRODUCTS_SAGA';

export const GET_REQUIRED_INGREDIENTS = 'GET_REQUIRED_INGREDIENTS';
export const GET_REQUIRED_INGREDIENTS_SAGA = 'GET_REQUIRED_INGREDIENTS_SAGA';
