export const SET_AUTH = 'SET_AUTH';
export const CHECK_AUTH_SAGA = 'SET_AUTH_SAGA';

export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';

export const AUTH_SAGA = 'AUTH_SAGA';
export const SIGN_OUT_SAGA = 'SIGN_OUT_SAGA';

export const SET_USER_INTOLERANCES = 'SET_USER_INTOLERANCES';
export const GET_USER_INTOLERANCES_SAGA = 'GET_USER_INTOLERANCES_SAGA';
export const SET_USER_INTOLERANCES_SAGA = 'SET_USER_INTOLERANCES_SAGA';
