export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SAGA = 'ADD_PRODUCT_SAGA';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SAGA = 'DELETE_PRODUCT_SAGA';

export const RESET_PRODUCTS_LOADED = 'RESET_PRODUCTS_LOADED';
